<html>
    <head>
        <meta charset="utf-8" />
        <title><?php echo $this->title ?> | amo</title>
        <link rel="stylesheet" href="css/app.css">
    </head>
    <body>
        <nav class="navbar navbar-dark bg-dark">
            <div class="container">
                <a class="navbar-brand" href="/">amo</a>
            </div>
        </nav>

        <div class="container pt-lg-3">
            <h2 class="mb-lg-3"><?php echo $this->title ?></h2>
            <?php include_once dirname(__DIR__) . '/templates/' . $this->template . '.phtml'; ?>
        </div>

    </body>
</html>
